### ISSUE TITLE
Data Export Using CLI

### ISSUE THREAD

**Issue by surajnaircaltech** [Cvedia/cvedia-cli#7]
Hello,

I have installed the command line tool, but am running into some issues when trying to download a dataset. My OS is a fresh Ubuntu 16.04 which has followed the commands for installation outlined in the installation guide.

The error I get is this:

```
2017-03-23 05:25:54,290 ERROR [default] Could not open python module folder at ./python/
2017-03-23 05:25:54,291 INFO  [default] We have LUA in main function
2017-03-23 05:25:54,291 ERROR [default] Could not open lua module folder at ./lua/
2017-03-23 05:25:54,733 INFO  api.cpp:67] API version: 1
2017-03-23 05:25:54,733 INFO  api.cpp:68] Welcome to Cvedia export API
2017-03-23 05:25:54,733 INFO  metadb.cpp:45] Initializing MetaDb
2017-03-23 05:25:54,733 INFO  metadb.cpp:46] SQlite3 version 3.11.0 (3011000)
2017-03-23 05:25:54,747 INFO  metadb.cpp:103] New Meta Db created
2017-03-23 05:25:54,748 INFO  csvwriter.cpp:26] Initializing CsvWriter
2017-03-23 05:25:54,748 INFO  api.cpp:97] Fetching dataset metadata at http://api.cvedia.com/1/RSDzxCz06v6FjuXAYznIiuJCTAxANusK/meta
2017-03-23 05:25:55,180 ERROR api.cpp:116] Could not get stats for JobID. Does it exist?
2017-03-23 05:25:55,181 ERROR cvedia.cpp:449] Failed to fetch metadata for dataset
```

This is for the CIFAR-10 dataset where I made no real alterations. I have experienced the same error on other datasets as well. Is there some additional information that needs to be provided with the `cvedia` command? Right now I directly copy the CLI export provided by the UI. 

Thanks!

**Comment by aescarcha** [comment]
Hi surajnaircaltech,

We found the issue, working on it now, I will post this when its fixed ASAP.
As always thanks for the feedback :)

Best regards

**Comment by aescarcha** [comment]
Hi surajnaircaltech,

Issue should be fixed now, the problem was within the API, could you confirm its ok?

**Comment by surajnaircaltech** [comment]
Now the download appears to be working when I use a simple CIFAR-10 dataset with no augmentations. However, when I try to download from a project with the camelyon17 dataset, I get the same error as earlier.

Best,
Suraj

**Comment by aescarcha** [comment]
Hi, if you pull from master and recompile, the issue should be fixed.

    git pull origin master
    autoheader
    aclocal
    autoconf
    automake
    ./configure
    make
    make install

**Comment by surajnaircaltech** [comment]
Hi,

There still appears to be an issue. It starts the download, but then throws an error no file_id.diz. Note I left out the JobID because the data is for Camelyon 17. 

```
2017-03-24 21:06:54,448 ERROR [default] Could not open python module folder at ./python/
2017-03-24 21:06:54,448 INFO  [default] We have LUA in main function
2017-03-24 21:06:54,448 ERROR [default] Could not open lua module folder at ./lua/
2017-03-24 21:06:54,883 INFO  api.cpp:67] API version: 1
2017-03-24 21:06:54,883 INFO  api.cpp:68] Welcome to Cvedia export API
2017-03-24 21:06:54,883 INFO  metadb.cpp:45] Initializing MetaDb
2017-03-24 21:06:54,883 INFO  metadb.cpp:46] SQlite3 version 3.11.0 (3011000)
2017-03-24 21:06:54,900 INFO  metadb.cpp:103] New Meta Db created
2017-03-24 21:06:54,900 INFO  csvwriter.cpp:26] Initializing CsvWriter
2017-03-24 21:06:54,900 INFO  api.cpp:97] Fetching dataset metadata at http://api.cvedia.com/1/<JobID>/meta
2017-03-24 21:06:55,404 INFO  cvedia.cpp:469] Exporting the following sets:
2017-03-24 21:06:55,404 INFO  cvedia.cpp:472] train (60%)
2017-03-24 21:06:55,404 INFO  cvedia.cpp:472] test (40%)
2017-03-24 21:06:55,404 INFO  cvedia.cpp:472] validate (0%)
2017-03-24 21:06:55,404 INFO  cvedia.cpp:475] Using the following fields:
2017-03-24 21:06:55,404 INFO  cvedia.cpp:477] 0: image1
2017-03-24 21:06:55,404 INFO  cvedia.cpp:477] 1: ground
2017-03-24 21:06:55,404 INFO  curlreader.cpp:33] Initializing CurlReader
2017-03-24 21:06:55,405 INFO  curlreader.cpp:141] Number of download threads set to 100
2017-03-24 21:06:55,405 INFO  cvedia.cpp:486] Iteration #1
2017-03-24 21:06:55,405 INFO  cvedia.cpp:487] Total expected dataset size is 500
2017-03-24 21:06:55,405 INFO  api.cpp:204] Starting feed readahead thread
2017-03-24 21:06:59,656 ERROR api.cpp:348] ParseFeed() Error parsing JSON data
[=================================================================================================================] [500/500]
2017-03-24 21:08:26,354 INFO  cvedia.cpp:581] Downloaded 963336 bytes
2017-03-24 21:08:26,354 INFO  cvedia.cpp:582] Syncing batch to disk...
2017-03-24 21:08:26,381 ERROR cvedia.cpp:1003] http://arc.cvedia.com/sJ90rW128H128MB~0:sW190976H98816zD1,2/d8063a118d9f7f9d230755043a5cd036.ost.tar.gz did not contain a file_id.diz
[=================================================================================================================] [304/304]
```

It seems like data is being transferred, but (1) it is incomplete (only a small subset of the data I wanted transferred is transferred before the error is thrown) and (2) it is transferring collections which I did not want transferred - I selected specific collections to export (not including the base collection), but the small amount of data that was successfully transferred appears to be from Base.

**Comment by aescarcha** [comment]
Hi,
I'm not having the same issue using this line (ID masked)

     ./cvedia -j RSDzxCz06v6XXXXXX -o CSV

I get the following number of files, is it correct?

     1785 test.txt
     5390 train.txt
     1785 validate.txt

**Comment by rorph** [comment]
@surajnaircaltech Sorry for the delay on this. We had a few problems with the API, it's all back to work now, you don't need to do any change on your end. I'd recommend you delete your local cache.

Use batch size 1000 (`-b 1000`) , there's one pending bug we still need to fix.

Please be aware that 17's TEST may contain empty (white) images, there's nothing we can do at moment as they are broken on the source.

Let us know if you have any other questions / issues.

**Comment by surajnaircaltech** [comment]
Ok I am able to successfully download the data. It still raises a ParseError, but data is being downloaded so there doesn't seem to be an issue.

Thanks!
